"""empty message

Revision ID: 5d79edc7b4c9
Revises: 2c72efad947b
Create Date: 2025-07-02 04:52:25.344929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d79edc7b4c9'
down_revision: Union[str, Sequence[str], None] = '2c72efad947b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_message', sa.String(), nullable=False))
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('type_message')

    # ### end Alembic commands ###
