"""empty message

Revision ID: cc63177b0412
Revises: 2edf825fe9f3
Create Date: 2025-07-01 13:01:24.405611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc63177b0412'
down_revision: Union[str, Sequence[str], None] = '2edf825fe9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum('NEW', 'PENDING', 'DONE', name='status')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('Chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', status_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chat', schema=None) as batch_op:
        batch_op.drop_column('status')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
